# Generated by Django 4.1 on 2023-02-01 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentorat', '0002_user_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
    ]
